### ISSUE TITLE
Missing proper citation and attribution

### ISSUE THREAD

**Issue by jrosebr1** [behl1anmol/VideoStreamingFlask#1]
Hi @behl1anmol -- it's come to my attention that you are using code and images from [my PyImageSearch tutorial](https://www.pyimagesearch.com/2019/09/02/opencv-stream-video-to-web-browser-html-page/) on your own Medium article with proper citation/attribution:

https://medium.com/datadriveninvestor/video-streaming-using-flask-and-opencv-c464bf8473d6

My FAQ clearly states that if you use images or code from my tutorials that you need to properly cite them:

https://www.pyimagesearch.com/faqs/single-faq/how-do-i-reference-or-cite-one-of-your-blog-posts-books-or-courses

I request that you update _both_ this GitHub repo README _and_ your article to properly cite the work. Please do not take advantage of free resources you learn from by not citing them.

**Comment by behl1anmol** [comment]
@jrosebr1 I apologize for my mistake sir. I have used the image from your blog and I will update my readme and my blog with proper citation.

**Comment by behl1anmol** [comment]
@jrosebr1 I have properly mentioned in the image caption with source.

**Comment by jrosebr1** [comment]
@behl1anmol Thanks, but you need to link to the original blog post (not the raw image itself). Here is what you should be linking to:

https://www.pyimagesearch.com/2019/09/02/opencv-stream-video-to-web-browser-html-page/

**Comment by behl1anmol** [comment]
@jrosebr1  Done sir, I have linked the original blog.

**Comment by behl1anmol** [comment]
@jrosebr1 Done Sir, I have attached the link to complete blog post.
